[[locations]]
file = "pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/pyproject.toml"
type = "pyproject-version"

[[locations]]
file = "python/{{ cookiecutter.project_slug }}/__init__.py"
type = "python-dunder"

[[locations]]
file = "python/{{ cookiecutter.project_slug }}/__init__.py"
type = "python-version-info"

[[locations]]
file = "CMakeLists.txt"
type = "cmake-project"

[[locations]]
file = "include/{{ cookiecutter.project_slug }}/{{ cookiecutter.project_slug }}.h"
type = "c-define"
prefix = "{{ cookiecutter.project_prefix }}"

[[locations]]
file = "swig/{{ cookiecutter.project_slug }}.i"
type = "c-define"
prefix = "{{ cookiecutter.project_prefix }}"

[[locations]]
file = "tests/python/test_{{ cookiecutter.project_slug }}.py"
type = "custom"
template = '{{ cookiecutter.project_slug }}\.__version__ == "{version}"'
label = "test-version-string"

[[locations]]
file = "tests/python/test_{{ cookiecutter.project_slug }}.py"
type = "custom"
template = '{{ cookiecutter.project_slug }}\.__version_info__ == \({info_tuple}\)'
label = "test-version-info"
